// ======= for Calander Data ==============

// helper to generate dates in current month/year
const makeDate = (day, hour, minute = 0) => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), day, hour, minute);
};



export const calanderData = {
    flights: [
        {
            voucher: "0524",
            traveler: "Huzaifa Sajjad",
            airline: "PIA",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "PK213",
            avatar: "https://i.pravatar.cc/40?u=huzaifa", // dummy avatar
            start: makeDate(8, 8, 0),  // 11th of current month, 8:00 AM
            end: makeDate(8, 9, 0),
        },

        {
            voucher: "0525",
            traveler: "Ali Khan",
            airline: "FlyDubai",
            from: "LHE",
            to: "DXB",
            class: "Business",
            flight: "FZ331",
            avatar: "https://i.pravatar.cc/40?u=ali",
            start: makeDate(12, 10, 0),
            end: makeDate(12, 12, 0),
        },
        {
            voucher: "0526",
            traveler: "Fayaz Khan",
            airline: "Emirates",
            from: "LHE",
            to: "DXB",
            class: "Economy",
            flight: "EK623",
            avatar: "https://i.pravatar.cc/40?u=fayaz",
            start: makeDate(12, 10, 0),
            end: makeDate(12, 12, 0),
        },
        {
            voucher: "0524",
            traveler: "Huzaifa Sajjad",
            airline: "PIA",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "PK213",
            avatar: "https://i.pravatar.cc/40?u=huzaifa",
            start: makeDate(11, 8, 0),
            end: makeDate(11, 9, 0),
        },
        {
            voucher: "0524",
            traveler: "Haris Sajjad",
            airline: "PIA",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "PK213",
            avatar: "https://i.pravatar.cc/40?u=huzaifa",
            start: makeDate(10, 12, 0),
            end: makeDate(10, 14, 0),
        },
        {
            voucher: "0524",
            traveler: "Salman Sajjad",
            airline: "PIA",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "PK213",
            avatar: "https://i.pravatar.cc/40?u=huzaifa",
            start: makeDate(10, 12, 0),
            end: makeDate(10, 14, 0),
        },
        {
            voucher: "0524",
            traveler: "Ali Sajjad",
            airline: "PIA",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "PK213",
            avatar: "https://i.pravatar.cc/40?u=huzaifa",
            start: makeDate(10, 12, 0),
            end: makeDate(10, 14, 0),
        },
        {
            voucher: "0524",
            traveler: "Arham Sajjad",
            airline: "PIA",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "PK213",
            avatar: "https://i.pravatar.cc/40?u=huzaifa",
            start: makeDate(10, 12, 0),
            end: makeDate(10, 14, 0),
        },
        {
            voucher: "0524",
            traveler: "Arham Sajjad",
            airline: "PIA",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "PK213",
            avatar: "https://i.pravatar.cc/40?u=huzaifa",
            start: makeDate(10, 10, 0),
            end: makeDate(10, 12, 0),
        },
    ],

    hotels: [
        {
            voucher: "1021",
            traveler: "Ahmed Raza",
            hotel: "Marriott Hotel",
            from: "KHI",
            to: "DXB",
            class: "Deluxe",
            bookingId: "HTL213",
            avatar: "https://i.pravatar.cc/40?u=ahmed",
            start: makeDate(8, 14, 0), // 14th of current month, 8:00 AM
            end: makeDate(8, 16, 0),
        },
        {
            voucher: "1022",
            traveler: "Sana Khan",
            hotel: "Hilton Dubai",
            from: "LHE",
            to: "DXB",
            class: "Suite",
            bookingId: "HTL331",
            avatar: "https://i.pravatar.cc/40?u=sana",
            start: makeDate(12, 12, 0),
            end: makeDate(12, 15, 0),
        },
        {
            voucher: "1023",
            traveler: "Bilal Hussain",
            hotel: "Atlantis The Palm",
            from: "ISB",
            to: "DXB",
            class: "Executive",
            bookingId: "HTL623",
            avatar: "https://i.pravatar.cc/40?u=bilal",
            start: makeDate(12, 18, 0),
            end: makeDate(12, 21, 0),
        },
        {
            voucher: "1024",
            traveler: "Ayesha Malik",
            hotel: "Burj Al Arab",
            from: "KHI",
            to: "DXB",
            class: "Luxury",
            bookingId: "HTL999",
            avatar: "https://i.pravatar.cc/40?u=ayesha",
            start: makeDate(11, 10, 0),
            end: makeDate(11, 13, 0),
        },
        {
            voucher: "1025",
            traveler: "Usman Ali",
            hotel: "Sheraton Grand",
            from: "LHE",
            to: "DXB",
            class: "Standard",
            bookingId: "HTL555",
            avatar: "https://i.pravatar.cc/40?u=usman",
            start: makeDate(10, 15, 0),
            end: makeDate(10, 18, 0),
        },
        {
            voucher: "1026",
            traveler: "Maria Javed",
            hotel: "Ritz-Carlton",
            from: "KHI",
            to: "DXB",
            class: "Deluxe",
            bookingId: "HTL777",
            avatar: "https://i.pravatar.cc/40?u=maria",
            start: makeDate(9, 20, 0),
            end: makeDate(9, 23, 0),
        },
        {
            voucher: "1027",
            traveler: "Omar Farooq",
            hotel: "Jumeirah Beach Hotel",
            from: "ISB",
            to: "DXB",
            class: "Suite",
            bookingId: "HTL888",
            avatar: "https://i.pravatar.cc/40?u=omar",
            start: makeDate(9, 25, 0),
            end: makeDate(9, 28, 0),
        },
        {
            voucher: "1028",
            traveler: "Fatima Noor",
            hotel: "Grand Hyatt",
            from: "KHI",
            to: "DXB",
            class: "Executive",
            bookingId: "HTL444",
            avatar: "https://i.pravatar.cc/40?u=fatima",
            start: makeDate(9, 30, 0),
            end: makeDate(10, 2, 0),
        },
    ],
    tours: [
        {
            voucher: "2011",
            traveler: "Ahmed Raza",
            airline: "PIA",
            tourHotel: "Marriott Beach Resort",
            avatar: "https://i.pravatar.cc/40?u=ahmed",
            start: makeDate(9, 30, 0),
            end: makeDate(10, 5, 0),
        },
        {
            voucher: "2012",
            traveler: "Sana Khan",
            airline: "Emirates",
            tourHotel: "Hilton Desert Safari",
            avatar: "https://i.pravatar.cc/40?u=sana",
            start: makeDate(10, 2, 0),
            end: makeDate(10, 7, 0),
        },
        {
            voucher: "2013",
            traveler: "Bilal Hussain",
            airline: "Qatar Airways",
            tourHotel: "Atlantis Adventure Resort",
            avatar: "https://i.pravatar.cc/40?u=bilal",
            start: makeDate(9, 7, 0),
            end: makeDate(9, 12, 0),
        },
        {
            voucher: "2014",
            traveler: "Ayesha Malik",
            airline: "Turkish Airlines",
            tourHotel: "Burj Al Safari Hotel",
            avatar: "https://i.pravatar.cc/40?u=ayesha",
            start: makeDate(10, 7, 0),
            end: makeDate(10, 12, 0),
        },
        {
            voucher: "2015",
            traveler: "Usman Ali",
            airline: "Etihad",
            tourHotel: "Sheraton Coastal Retreat",
            avatar: "https://i.pravatar.cc/40?u=usman",
            start: makeDate(12, 9, 0),
            end: makeDate(12, 14, 0),
        },
        {
            voucher: "2016",
            traveler: "Maria Javed",
            airline: "Saudi Airlines",
            tourHotel: "Ritz-Carlton Desert Camp",
            avatar: "https://i.pravatar.cc/40?u=maria",
            start: makeDate(10, 11, 0),
            end: makeDate(10, 16, 0),
        },
        {
            voucher: "2017",
            traveler: "Omar Farooq",
            airline: "Flydubai",
            tourHotel: "Jumeirah Adventure Resort",
            avatar: "https://i.pravatar.cc/40?u=omar",
            start: makeDate(10, 13, 0),
            end: makeDate(10, 18, 0),
        },
        {
            voucher: "2018",
            traveler: "Fatima Noor",
            airline: "Air Arabia",
            tourHotel: "Grand Hyatt Safari Lodge",
            avatar: "https://i.pravatar.cc/40?u=fatima",
            start: makeDate(8, 15, 0),
            end: makeDate(8, 20, 0),
        },
    ],
    transfers: [
        {
            voucher: "0524",
            traveler: "Huzaifa Sajjad",
            airline: "PIA",
            time: "08:00 AM",
            tourHotel: "Marriott Beach Resort",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "PK213",
            avatar: "https://i.pravatar.cc/40?u=huzaifa",
            start: makeDate(8, 8, 8),
            end: makeDate(8, 8, 12),
        },
        {
            voucher: "0525",
            traveler: "Ayesha Khan",
            airline: "Emirates",
            time: "09:30 AM",
            tourHotel: "Hilton Desert Safari",
            from: "LHE",
            to: "DXB",
            class: "Business",
            flight: "EK512",
            avatar: "https://i.pravatar.cc/40?u=ayesha",
            start: makeDate(9, 21, 9),
            end: makeDate(9, 21, 13),
        },
        {
            voucher: "0526",
            traveler: "Bilal Hussain",
            airline: "Qatar Airways",
            time: "10:00 AM",
            tourHotel: "Atlantis Adventure Resort",
            from: "ISB",
            to: "DXB",
            class: "Economy",
            flight: "QR781",
            avatar: "https://i.pravatar.cc/40?u=bilal",
            start: makeDate(12, 10, 10),
            end: makeDate(12, 11, 14),
        },
        {
            voucher: "0527",
            traveler: "Maria Javed",
            airline: "Turkish Airlines",
            time: "07:45 AM",
            tourHotel: "Ritz-Carlton Desert Camp",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "TK431",
            avatar: "https://i.pravatar.cc/40?u=maria",
            start: makeDate(9, 23, 7),
            end: makeDate(9, 23, 11),
        },
        {
            voucher: "0528",
            traveler: "Omar Farooq",
            airline: "Etihad",
            time: "11:15 AM",
            tourHotel: "Jumeirah Adventure Resort",
            from: "ISB",
            to: "DXB",
            class: "Business",
            flight: "EY205",
            avatar: "https://i.pravatar.cc/40?u=omar",
            start: makeDate(9, 24, 11),
            end: makeDate(9, 24, 15),
        },
        {
            voucher: "0529",
            traveler: "Fatima Noor",
            airline: "Flydubai",
            time: "06:30 AM",
            tourHotel: "Grand Hyatt Safari Lodge",
            from: "KHI",
            to: "DXB",
            class: "Economy",
            flight: "FZ901",
            avatar: "https://i.pravatar.cc/40?u=fatima",
            start: makeDate(9, 25, 6),
            end: makeDate(9, 25, 10),
        },
        {
            voucher: "0530",
            traveler: "Usman Ali",
            airline: "Saudi Airlines",
            time: "08:45 AM",
            tourHotel: "Sheraton Coastal Retreat",
            from: "LHE",
            to: "DXB",
            class: "Business",
            flight: "SV332",
            avatar: "https://i.pravatar.cc/40?u=usman",
            start: makeDate(9, 26, 8),
            end: makeDate(9, 26, 12),
        },
        {
            voucher: "0531",
            traveler: "Sana Khan",
            airline: "Air Arabia",
            time: "09:00 AM",
            tourHotel: "Hilton Desert Safari",
            from: "LHE",
            to: "DXB",
            class: "Economy",
            flight: "G9 112",
            avatar: "https://i.pravatar.cc/40?u=sana",
            start: makeDate(9, 27, 9),
            end: makeDate(9, 27, 13),
        },
    ],










}